
# travis config

sudo: required
language: r


addons:
  apt:
    packages:
      - libxml2-dev

r:
 - release
 - oldrel
 - devel



before_install:
  - R -e "install.packages(c('devtools','roxygen2','testthat'))"
  - R -e "devtools::install_deps('./pkg')"
  - R -e "devtools::load_all('./pkg'); devtools::document('./pkg')"
  - cd ./pkg

r_packages:
  - covr
  - rmarkdown


after_success:
  - Rscript -e 'library(covr);coveralls()'

notifications:
  email:
    on_success: change
    on_failure: change


